comment:
  gitalk:
    enable: true
    owner: chenhuiz
    admin: chenhuiz
    repo: https://github.com/ChenhuiZhang/blog.git
    ClientID:
    ClientSecret:
    labels: 'gitalk'
    distractionFreeMode: true
socialList:
  - name: telegram
    url:
  - name: github
    url: https://github.com/ChenhuiZhang
  - name: mail
    url: zhangchenhui2006@gmail.com
highlight:
  light: https://cdn.staticfile.org/highlight.js/11.5.0/styles/github.min.css
  dark: https://cdn.staticfile.org/highlight.js/11.5.0/styles/github-dark.min.css
copyright:
  enable: true
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
